name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Show Project Files
        run: ls -la

      - name: Run Pipeline
        run: echo "CI/CD Pipeline executed successfully"
